task_group: pick_and_place
task_id: place_blue_on_blue_plate
title: "Place blue cube on blue plate"
description: "Pick the blue cube and place it on the blue plate."
difficulty: 3
time_limit_s: 150

success:
  collisions_true:
    - [box_blue, plate_blue]
  collisions_false:
    - [box_blue, table_lightgray]

fail:
  collisions_true:
    - [box_blue, ground_plane]
    - [cobot, table_lightgray]
    - [cobot, cobot]
  collisions_false: []
