# config/levels/touch/level_03_cube_blue.yaml
task_group: touch
task_id: touch_blue_cube
title: "Touch the blue cube"
description: "Move the gripper to make contact with the blue cube."
difficulty: 3
time_limit_s: 60

success:
  collisions_true:
    - [cobot, box_blue]
  collisions_false: []

fail:
  collisions_true:
    - [box_blue, ground_plane]   # fell off the table
    - [cobot, table_lightgray]
    - [cobot, cobot]  # collided with the table
  collisions_false: []
